[package]
name = "rust-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-server = "2.6.0"
actix-web = "4.11.0"
chrono = "0.4.42"
dotenv = "0.15.0"
env_logger = "0.11.8"
serde = "1.0.226"
serde_json = "1.0.145" 
sqlx = "0.8.6"
uuid = "1.18.1"
