version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
    ports:
      - '5050:80'
volumes:
  progresDB: